spring:
  kafka:
    bootstrap-servers: 218.39.215.185:9092
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mykeedatabase.c3ici960koc9.ap-northeast-2.rds.amazonaws.com:3306/socket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: thfwlrgkssk1!

  #      url: jdbc:h2:mem:testdb
  #      url: jdbc:h2:tcp://localhost/~/auctiondb
  #      username: sa
  #      password:
  #      driver-class-name: org.h2.Driver
  #   mem:testdb;MODE=MYSQL

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

